# Generated by Django 4.0.3 on 2022-03-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_hahas_post_loves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
